/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ConsultationRegist } from "./ConsultationRegist";
export * as factories from "./factories";
export { ConsultationRegist__factory } from "./factories/ConsultationRegist__factory";
