/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as consultationSol from "./consultation.sol";
export * as registrationSol from "./registration.sol";
export * as rolesSol from "./roles.sol";
export * as userSol from "./user.sol";
