/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as konsultasiSol from "./konsultasi.sol";
export * as registrasiSol from "./registrasi.sol";
export * as rolesSol from "./roles.sol";
export * as userSol from "./user.sol";
