/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as konsultasiSol from "./konsultasi.sol";
export type { konsultasiSol };
import type * as registrasiSol from "./registrasi.sol";
export type { registrasiSol };
import type * as rolesSol from "./roles.sol";
export type { rolesSol };
import type * as userSol from "./user.sol";
export type { userSol };
export * as factories from "./factories";
export type { ConsultationResult } from "./konsultasi.sol/ConsultationResult";
export { ConsultationResult__factory } from "./factories/konsultasi.sol/ConsultationResult__factory";
export type { ConsultationRegist } from "./registrasi.sol/ConsultationRegist";
export { ConsultationRegist__factory } from "./factories/registrasi.sol/ConsultationRegist__factory";
export type { UserRoles } from "./roles.sol/UserRoles";
export { UserRoles__factory } from "./factories/roles.sol/UserRoles__factory";
export type { UserData } from "./user.sol/UserData";
export { UserData__factory } from "./factories/user.sol/UserData__factory";
