/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as consultationSol from "./consultation.sol";
export type { consultationSol };
import type * as registrationSol from "./registration.sol";
export type { registrationSol };
import type * as rolesSol from "./roles.sol";
export type { rolesSol };
import type * as userSol from "./user.sol";
export type { userSol };
export * as factories from "./factories";
export type { ConsultationResult } from "./consultation.sol/ConsultationResult";
export { ConsultationResult__factory } from "./factories/consultation.sol/ConsultationResult__factory";
export type { ConsultationRegist } from "./registration.sol/ConsultationRegist";
export { ConsultationRegist__factory } from "./factories/registration.sol/ConsultationRegist__factory";
export type { UserRoles } from "./roles.sol/UserRoles";
export { UserRoles__factory } from "./factories/roles.sol/UserRoles__factory";
export type { UserData } from "./user.sol/UserData";
export { UserData__factory } from "./factories/user.sol/UserData__factory";
